/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gitscheduler2;

/**
 *
 * @author Seamus O Connor
 */




import com.toedter.calendar.JCalendar;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import static java.time.Instant.now;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;




public class SchedulerGUI extends javax.swing.JFrame {

    /**
     * 
     * 
     * 
     * 
     * 
     * Creates new form SchedulerGUI
     */
    
    
  
    
    Statement stmt;
   
    
    public SchedulerGUI() {
        initComponents();
        
        
        
        
    }

    
    
    
    
    
    
             
        
        
        public  void loadTable()  {
        
            Methods method = new Methods();
      //Connection  con = method.con;
     ResultSet rs = method.rs;
             
     
      if (rs!=null)JTableSchedule.setModel(DbUtils.resultSetToTableModel(rs));
        try {
            if (rs!=null)rs.close();
        } catch (Exception ex) {
            Logger.getLogger(SchedulerGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
      
        }
        
        
        public void loadDefaultTable() {
            
            
               Methods method = new Methods();
               
      //Connection  con = method.con;
     ResultSet rs2 = method.rs2;
     
        
     if (rs2!=null)JTableSchedule.setModel(DbUtils.resultSetToTableModel(rs2));
     
     
     try {
         if (rs2!=null)rs2.close();
     } catch (Exception ex) {
          Logger.getLogger(SchedulerGUI.class.getName()).log(Level.SEVERE, null, ex);
     }
     
        
        
        }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableSchedule = new javax.swing.JTable();
        WorkingsPanel = new javax.swing.JPanel();
        JButtonLoad = new javax.swing.JButton();
        JNewButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JTableSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JTableSchedule);

        javax.swing.GroupLayout TablePanelLayout = new javax.swing.GroupLayout(TablePanel);
        TablePanel.setLayout(TablePanelLayout);
        TablePanelLayout.setHorizontalGroup(
            TablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 904, Short.MAX_VALUE)
        );
        TablePanelLayout.setVerticalGroup(
            TablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        JButtonLoad.setText("Load Schedule");
        JButtonLoad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JButtonLoadMouseClicked(evt);
            }
        });
        JButtonLoad.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                JButtonLoadPropertyChange(evt);
            }
        });

        JNewButton.setText("New Database");
        JNewButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JNewButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout WorkingsPanelLayout = new javax.swing.GroupLayout(WorkingsPanel);
        WorkingsPanel.setLayout(WorkingsPanelLayout);
        WorkingsPanelLayout.setHorizontalGroup(
            WorkingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WorkingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JButtonLoad)
                .addGap(36, 36, 36)
                .addComponent(JNewButton)
                .addContainerGap(614, Short.MAX_VALUE))
        );
        WorkingsPanelLayout.setVerticalGroup(
            WorkingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WorkingsPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(WorkingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButtonLoad)
                    .addComponent(JNewButton))
                .addContainerGap(260, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(WorkingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WorkingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JCalendarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_JCalendarPropertyChange

        

System.out.println(JCalendar.getDate());// TODO add your handling code here:
       
        
           
        
    }//GEN-LAST:event_JCalendarPropertyChange

    private void JButtonLoadPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_JButtonLoadPropertyChange
        // TODO add your handling code here:
        
        
        
        
    }//GEN-LAST:event_JButtonLoadPropertyChange

    private void JButtonLoadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JButtonLoadMouseClicked
        // TODO add your handling code here:
        
        loadTable();
        
        
     
    }//GEN-LAST:event_JButtonLoadMouseClicked

    private void JCalendarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCalendarMouseClicked

        

// TODO add your handling code here:
    
    }//GEN-LAST:event_JCalendarMouseClicked

    private void JCalendarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JCalendarFocusGained
        // TODO add your handling code here:
    
    }//GEN-LAST:event_JCalendarFocusGained

    private void JCalendarCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_JCalendarCaretPositionChanged
        // TODO add your handling code here:
    
    }//GEN-LAST:event_JCalendarCaretPositionChanged

    private void JCalendarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JCalendarKeyPressed
     // TODO add your handling code here:
    }//GEN-LAST:event_JCalendarKeyPressed

    private void JCalendarVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_JCalendarVetoableChange
        // TODO add your handling code here:
     
    }//GEN-LAST:event_JCalendarVetoableChange

    private void JCalendarInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_JCalendarInputMethodTextChanged
        // TODO add your handling code here:
       
    }//GEN-LAST:event_JCalendarInputMethodTextChanged

    private void JNewButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JNewButtonMouseClicked
    
           Methods method = new Methods();
           method.createSchedule();
        
    }//GEN-LAST:event_JNewButtonMouseClicked

    
  public Date setSelectedDate() {
    Calendar cal = Calendar.getInstance();
   

     cal.setTime(JCalendar.getDate());
       Date Date3 = cal.getTime();
   
        return Date3;
        
        
      
        
        
    }
    
  
 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SchedulerGUI().setVisible(true);
                
            }
        });
        
     
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
  
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonLoad;
    private javax.swing.JButton JNewButton;
    private javax.swing.JTable JTableSchedule;
    private javax.swing.JPanel TablePanel;
    private javax.swing.JPanel WorkingsPanel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
